# Five Interesting Functions In Pytorch

An short introduction about PyTorch and about the chosen functions. 
    It’s a Python-based scientific computing package targeted at two sets of audiences:

  **A replacement for NumPy to use the power of GPUs**
  **a deep learning research platform that provides maximum flexibility and speed**
  
  Introduction to 5 functions in this Assignment
- torch.ceil(input, out=None)
    Returns a new tensor with the ceil of the elements of input, the smallest integer greater than or equal to each element.
- torch.clamp(input, min, max, out=None) → Tensor
    Clamp all elements in input into the range [ min, max ] and return a resulting tensor.
- torch.arange(start,end,step)
    Returns a 1-D tensor of values falling in between two values with steps provided.
-  torch.div(input, other, out=None)
    Divides each element of the input input with the scalar other and returns a new resulting tensor.
- torch.fmod(input, other, out=None)
    Computes the element-wise remainder of division.

In [2]:
#importing torch
import torch

## Function 1 -  torch.ceil(input, out=None)
    Returns a new tensor with the ceil of the elements of input, the smallest integer greater than or equal to each element.
### Parameters
   1) input (Tensor) – the input tensor.
   
   2) out (Tensor, optional) – the output tensor.


#### Example 1

In [28]:
a=torch.tensor([-0.5812, -1.4208, 1.0800,  0.5726])
a

tensor([-0.5812, -1.4208,  1.0800,  0.5726])

In [29]:
torch.ceil(a)

tensor([-0., -1.,  2.,  1.])

The above Example we can see that torch.ceil fucntion return tensor with the next number floating point

##### Example 2

In [26]:
c=torch.tensor([4/6, -1.0008, 6.0+(7/8),  -0.5726])
c

tensor([ 0.6667, -1.0008,  6.8750, -0.5726])

In [27]:
torch.ceil(c)

tensor([ 1., -1.,  7., -0.])

##### Example 3

In [22]:
#breakdown of function
b=torch.tensor([1, 1, 1,  1])
b


tensor([1, 1, 1, 1])

In [23]:
torch.ceil(b)

RuntimeError: ceil_vml_cpu not implemented for 'Long'

In above function it breakdown because while using this function we strickly required floating point data type.

## Function 2 - torch.clamp(input, min, max, out=None)

Clamp all elements in input into the range [min,max] and return a resulting tensor.

If input is of type FloatTensor or DoubleTensor, args min and max must be real numbers, otherwise they should be integers.

#### Parameters

1)input (Tensor) – the input tensor.

2)min (Number) – lower-bound of the range to be clamped to

3)max (Number) – upper-bound of the range to be clamped to

4)out (Tensor, optional) – the output tensor.

In [ ]:
#### Example 1

In [39]:
f21=torch.tensor([-2.5120,  0.1334, 0.9878, 0.0912])
f21

tensor([-2.5120,  0.1334,  0.9878,  0.0912])

In [40]:
torch.clamp(f21, min=-1.5, max=0.5)

tensor([-1.5000,  0.1334,  0.5000,  0.0912])

In [ ]:
#### Example 2

In [41]:
f22=torch.tensor([-2.,  0.1134, -1.9878, 0.9912])
f22

tensor([-2.0000,  0.1134, -1.9878,  0.9912])

In [42]:
torch.clamp(f22, min=-1.75, max=0.98)

tensor([-1.7500,  0.1134, -1.7500,  0.9800])

The Above to examples illustrate how the torch.clamp works.

This functions is really helpful when we decide to limit values of certain tensor to perform certain task

## Function 3 -torch.arange(start,end,step)

Returns a 1-D tensor of values falling in between two values with steps provided.
### Parameter
1) start(number)-The lower limit of values 

2) end(number)-The upper limit of values

3) step(number)- The step we want to skip or more

#### Example 1

In [43]:
torch.arange(start=-1,end=5,step=2)

tensor([-1,  1,  3])

We use intergers to define starting and end values here and we got expected result for it.

#### Example 2

In [45]:
torch.arange(1,2,0.5)

tensor([1.0000, 1.5000])

In this example it is clear that not only integers we can also use floating point numbers to get our required tensor.

#### Example 3

In [48]:
torch.arange([1,2,3])

TypeError: arange(): argument 'end' (position 1) must be Number, not list

We cannot pass list when creating a tensor using arange , it only accepts start , end and step as parameter.

## Function 4 - torch.div(input, other, out=None)

Divides each element of the input input with the scalar other and returns a new resulting tensor.
### Parameter

1)input (Tensor) – the input tensor

2)other (Number) – the number to be divided to each element of input

### Keyword Arguments

1)out (Tensor, optional) – the output tensor




#### Example 1

In [56]:
f41=torch.tensor([ 0.6310,  2.2774, -0.7872, 0.3729,  -5.4637])
f41

tensor([ 0.6310,  2.2774, -0.7872,  0.3729, -5.4637])

In [58]:
torch.div(f41, 0.7542)

tensor([ 0.8366,  3.0196, -1.0438,  0.4944, -7.2444])

#### Example 2

In [60]:
f42=torch.tensor([ 10,  2.24, 78.72, 78/68,  -5.])
f42

tensor([10.0000,  2.2400, 78.7200,  1.1471, -5.0000])

In [61]:
torch.div(f42, 19.7842)

tensor([ 0.5055,  0.1132,  3.9789,  0.0580, -0.2527])

The Above two Examples illustrate perfectly how the functions works


#### Example 3

In [64]:
f43=torch.tensor([ 10,  2.24, 78.72, 78/68,  0])
f43

tensor([10.0000,  2.2400, 78.7200,  1.1471,  0.0000])

In [65]:
torch.div(f43, 0)

tensor([inf, inf, inf, inf, nan])

Not Actual Breakdown but still it is obvious according to mathematically that we can't divide any number by 0.

This functions is really helpful when we are required to divide the whole set of values with a single number

## Function 5 -torch.fmod(input, other, out=None)

Computes the element-wise remainder of division.

The dividend and divisor may contain both for integer and floating point numbers. The remainder has the same sign as the dividend input.

When other is a tensor, the shapes of input and other must be broadcastable.

### Parameter
1)input (Tensor) – the dividend

2)other (Tensor or float) – the divisor, which may be either a number or a tensor of the same shape as the dividend

3)out (Tensor, optional) – the output tensor.

#### Example 1

In [71]:
torch.fmod(torch.tensor([-5., 9, -1, 0, 6, 3]), 3)

tensor([-2.,  0., -1.,  0.,  0.,  0.])

#### Example 2

In [72]:
torch.fmod(torch.tensor([1.7896, 2.6753, 3., 4/5, 5+7.8954]), 1.75)

tensor([0.0396, 0.9253, 1.2500, 0.8000, 0.6454])

#### Example 3

In [75]:
torch.fmod(torch.tensor([[-5., 9], [-1, 0], [6, 3]]), 3)

tensor([[-2.,  0.],
        [-1.,  0.],
        [ 0.,  0.]])

The above examples clearly illustrate various possible input of various values and their respective output tensor.

As such I didn't get any breakdown but if you insert according to parameter you will get your required output.

## Conclusion

In this assignment I went through various function of different functionality and learnt that there are really enormous scope with our tensors.
I used torch.clamp() and torch.ceil() which helps is obtaining tensors of target limits and boundries.
I used torch.div() and torch.fmod() which helps to get remainder and modulus of whole set of vales of tensor.
I used torch.arranged() that also helps to build a tensor with certain values and steps along with bountries.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [76]:
!pip install jovian --upgrade --quiet

In [77]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: 